### ISSUE TITLE
Plugin approval

### ISSUE THREAD

**Issue by NyakudyaA** [TheFunEmbargo/QGIS-Gather-Connector#1]
# problem

Please remove https://github.com/TheFunEmbargo/QGIS-Gather-Connector/tree/main/__pycache__, it's autogenerated on install.

Also fix the plugin homepage in metadata.txt to reference a link that relates to the plugin not the generic site

**Comment by TheFunEmbargo** [comment]
Hi NyakudyaA,

I've removed the pycache. I made a small ui & code change adding a folder dialog, so have also incremented the version.

Cheers for reviewing this.

**Comment by NyakudyaA** [comment]
@TheFunEmbargo I do not see the section on your website, please fix the Plugin home page to link to that section you specifically mention

**Comment by NyakudyaA** [comment]
ping @TheFunEmbargo

**Comment by TheFunEmbargo** [comment]
Hi @NyakudyaA 

Sorry for the delay. Have made the changes you requested: https://plugins.qgis.org/plugins/gatherconnect/
